# Generated by Django 5.1.4 on 2025-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibraryshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_url', models.URLField(max_length=500)),
            ],
        ),
    ]
